# -*- coding: utf-8 -*-
"""cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZwinB4n6qkg_ooVoXnqy65ZhqsDV9n9

Step 1: Import the libraries we need
"""

import pandas as pd       # pandas handles all data loading and cleaning
import numpy as np        # numpy helps with numerical operations

"""Step 2: Load your CSV file into a DataFrame
A DataFrame is like an Excel spreadsheet — rows and columns
"""

# OPTION 1: Upload file manually (Google Colab)
from google.colab import files
uploaded = files.upload()

df = pd.read_csv('toronto_data.csv')

# OPTION 2: Load from local path (if not using Colab)
file_path = "your_file.csv"
df = pd.read_csv(file_path)

# OPTION 3: Load directly from a URL (e.g., GitHub raw link)
file_url = "https://raw.githubusercontent.com/username/repo/main/data.csv"
df = pd.read_csv(file_url)

print("✅ Data loaded successfully")

"""Step 3: Get a first look at the data"""

print("🔍 DATA PREVIEW")
print(df.head())

print("\n📏 SHAPE:", df.shape)

print("\n📋 INFO")
print(df.info())

print("\n📊 SUMMARY")
print(df.describe(include='all'))

"""Step 4: Clean column names"""

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w]+", "_", regex=True)
)

print("\n✅ Column names standardized")

"""Step5: Remove empty rows/Columns"""

df.dropna(how='all', inplace=True)      # Drop completely empty rows
df.dropna(axis=1, how='all', inplace=True)  # Drop completely empty columns

"""Step 6: Remove Duplicates"""

duplicates = df.duplicated().sum()
print(f"\n🔍 Duplicate rows found: {duplicates}")

df.drop_duplicates(inplace=True)

"""Step 7: Handle Missing values"""

print("\n🔍 Missing values per column:")
print(df.isnull().sum())

for col in df.columns:
    if df[col].dtype == 'object':
        # Fill text columns with most frequent value
        if df[col].mode().empty:
            df[col] = df[col].fillna("unknown")
        else:
            df[col] = df[col].fillna(df[col].mode()[0])
    else:
        # Fill numeric columns with median (more robust than mean)
        df[col] = df[col].fillna(df[col].median())

print("✅ Missing values handled")

"""Step 8: Fix Data Types (Auto Detect)"""

for col in df.columns:
    # Try converting to numeric
    df[col] = pd.to_numeric(df[col], errors='ignore')

    # Try converting to datetime
    try:
        df[col] = pd.to_datetime(df[col], errors='ignore')
    except:
        pass

print("\n✅ Data types optimized")

"""Step 9: Clean Text Columns"""

text_cols = df.select_dtypes(include='object').columns

for col in text_cols:
    df[col] = df[col].str.strip().str.lower()

print("✅ Text columns cleaned")

"""Step 10: Remove Outliers (Numeric onl)"""

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[(df[col] >= lower) & (df[col] <= upper)]

print("✅ Outliers handled (IQR method)")

"""Step 11: Final Validation"""

print("\n✅ FINAL VALIDATION")

print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

print("\nMissing values remaining:")
print(df.isnull().sum().sum())

print("\nDuplicate rows remaining:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

"""Step 12: Export Clean Data"""

output_file = "clean_data.csv"
df.to_csv(output_file, index=False)

print(f"\n💾 Cleaned data saved to: {output_file}")

"""Check Execution Time"""

print(f"Total time: {round(time.time() - start, 2)} seconds")