# -*- coding: utf-8 -*-
"""eda_template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1swBOiM3TVZo2BXjCQdbLMTKfC_AQtYtW

Step1: Import the libraries we need
"""

import pandas as pd
import numpy as np

"""Step 2: Load the dataset"""

from google.colab import files
uploaded = files.upload()

FILE_PATH = "clean_data.csv" # Change this to your file name
TARGET_COLUMN = None   # e.g. "sales" (set to None if not applicable)

df = pd.read_csv(FILE_PATH)
print(f"Dataset loaded: {df.shape[0]} rows, {df.shape[1]} columns\n")

# Auto-detect column types
numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = df.select_dtypes(include='object').columns.tolist()

"""SECTION 1: SUMMARY"""

print("=== STATISTICAL SUMMARY ===")
print(df[numeric_cols].describe().round(2))
print()

print("=== MEDIAN VALUES ===")
print(df[numeric_cols].median().round(2))
print()

"""SECTION 2: CATEGORICAL ANALYSIS"""

print("=== UNIQUE VALUES PER COLUMN ===")
print(df.nunique())
print()

for col in categorical_cols:
    print(f"=== TOP VALUES: {col} ===")
    print(df[col].value_counts().head(10))
    print()

"""SECTION 3: GROUPED ANALYSIS"""

if TARGET_COLUMN and TARGET_COLUMN in df.columns:

    print(f"=== GROUPED ANALYSIS ON: {TARGET_COLUMN} ===")

    for col in categorical_cols:
        print(f"\n--- {col} vs {TARGET_COLUMN} ---")

        summary = df.groupby(col)[TARGET_COLUMN].agg(
            count='count',
            total='sum',
            mean='mean',
            median='median',
            std='std'
        ).round(2)

        print(summary.sort_values(by='total', ascending=False).head(10))

""" SECTION 4: CORRELATION"""

if len(numeric_cols) > 1:
    print("\n=== CORRELATION MATRIX ===")
    corr = df[numeric_cols].corr().round(2)
    print(corr)

    if TARGET_COLUMN and TARGET_COLUMN in corr.columns:
        print(f"\n=== CORRELATION WITH {TARGET_COLUMN} ===")
        print(corr[TARGET_COLUMN].sort_values(ascending=False))

"""SECTION 5: OUTLIERS (ALL NUMERIC)"""

print("\n=== OUTLIER DETECTION (IQR) ===")

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"{col}: {len(outliers)} outliers")

"""SECTION 6: OPTIONAL EXPORT"""

print("\nEDA Completed ✅")